project:
  type: website
  output-dir: docs

website:
  repo-url: https://github.com/lmu-osc/Simulations-for-Advanced-Power-Analyses
  repo-actions: [edit, issue]
  favicon: images/LMU-OSC_favicon.jpg
  margin-header: |
    ![](/images/LMU-OSC_logo.jpg){width="175"}
    
  sidebar:
    style: "docked"
    search: true
    logo: images/LMU-OSC_logo_small.jpg
    contents:
      - index.qmd
      - section: "Models"
        contents:
          - LM1.qmd
          - LM2.qmd
          - GLM.qmd
          - LMM.qmd
          - SEM.qmd
      - section: "Bonuses"
        contents:
        - optimizing_code.qmd
        - how_many_iterations.qmd
        - SEM_fit_index.qmd
      - Resources.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      - includes/matomo.html

execute:
  cache: true

editor: source